# https://medium.com/@cmichel/how-to-deploy-a-create-react-app-with-github-actions-5e01f7a7b6b
name: Build Package

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install Packages
        run: yarn
      - name: test package
        run: yarn test
      - name: Build package
        run: yarn buildpackage
      - name: Build
        run: yarn build
